### CS5785 Homework 3 - Part II
Salvador Galarza

In [206]:
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans

In [192]:
X = np.load("science2k-doc-word.npy")
X

array([[-0.2521619, -0.2521619,  9.36371  , ..., -0.2521619, -0.2521619,
        -0.2521619],
       [-0.2875293, -0.2875293,  8.229864 , ..., -0.2875293, -0.2875293,
        -0.2875293],
       [-0.3634041, -0.3634041,  9.252468 , ..., -0.3634041, -0.3634041,
        -0.3634041],
       ...,
       [10.04846  , -0.7713402,  9.132197 , ..., -0.7713402, -0.7713402,
        -0.7713402],
       [11.00702  , -0.8423803, 10.38288  , ..., -0.8423803, -0.8423803,
        -0.8423803],
       [ 9.710337 , -0.7527946,  9.556191 , ..., -0.7527946, -0.7527946,
        -0.7527946]])

In [193]:
k_vals = list(range(1,21))
for k in k_vals:
    kmeans = KMeans(n_clusters=k, random_state=0).fit(X)
#     print(kmeans.score(X))

In [194]:
k = 7
kmeans = KMeans(n_clusters=k, random_state=0).fit(X)
kmeans.labels_

array([0, 0, 0, ..., 2, 3, 3], dtype=int32)

In [195]:
# d0 = kmeans.transform(X)[:,0]
# len(d0)

In [196]:
n = 10
k_cluster_n = []
d = []
for cluster in range(k):
    d.append(kmeans.transform(X)[:,cluster])
    k_cluster_n.append(np.sort(kmeans.transform(X)[:,cluster])[:n])
k_cluster_n

[array([ 98.28239856,  98.48908159, 102.06165291, 102.89865725,
        102.89865725, 102.89865725, 103.27514948, 103.98961673,
        104.2387512 , 104.79088186]),
 array([119.76983241, 120.02401255, 121.047961  , 121.35566407,
        122.14896801, 122.71754848, 123.60065629, 123.70363829,
        124.01889433, 124.33835193]),
 array([118.11861119, 119.53765681, 121.97434818, 122.2249341 ,
        122.71098243, 122.71907588, 122.983185  , 123.15302488,
        123.23263684, 123.65999715]),
 array([119.63150287, 119.90904439, 120.51801702, 120.69368682,
        120.74191267, 121.41409355, 121.7291652 , 122.02048981,
        122.44800836, 122.74516767]),
 array([105.9595827 , 106.16025321, 106.83800393, 111.05066964,
        113.19061361, 113.74088491, 113.93139329, 114.07321867,
        114.20387919, 114.76030901]),
 array([113.28674827, 113.5303577 , 136.65931416, 139.74510389,
        140.21732861, 141.34601588, 141.53304501, 141.74595632,
        142.14510135, 143.69904035]),
 arr

In [197]:
data = pd.read_csv('science2k-titles.txt', header=None)
data.columns = ["title"]

In [198]:
w = list(d[0])
print(sorted(range(len(w)), key=lambda k: w[k])[:10])

[519, 574, 499, 122, 123, 124, 90, 0, 453, 431]


In [199]:
for i in range(len(d)):
    print("Cluster Group {}".format(i))
    w = list(d[i])
    ind = sorted(range(len(w)), key=lambda k: w[k])[:10]
    for j in ind:
        print(data['title'][j])
    print("\n")

Cluster Group 0
Algorithmic Gladiators Vie for Digital Glory
Reopening the Darkest Chapter in German Science
National Academy of Sciences Elects New Members
Corrections and Clarifications: A Short Fe-Fe Distance in Peroxodiferric Ferritin: Control of Fe Substrate versus Cofactor Decay?
Corrections and Clarifications: Charon's First Detailed Spectra Hold Many Surprises
Corrections and Clarifications: Unearthing Monuments of the Yarmukians
Heretical Idea Faces Its Sternest Test
Archaeology in the Holy Land
Information Technology Takes a Different Tack
Movement Patterns in Spoken Language


Cluster Group 1
Population Dynamical Consequences of Climate Change for a Small Temperate Songbird
The Formation of Chondrules at High Gas Pressures in the Solar Nebula
Algorithmic Gladiators Vie for Digital Glory
Reopening the Darkest Chapter in German Science
Subducted Seamount Imaged in the Rupture Zone of the 1946 Nankaido Earthquake
Tectonic Implications of U-Pb Zircon Ages of the Himalayan Orogen

##### Comment on these results. What has the algorithm captured? How might such an algorithm be useful?

This algorithm captured the top 10 closest article titles to each cluster center. This may be useful by allowing us to identify the types of articles per cluster and classifying them. For example we can use NLP to classify these articles based on the title. 

#### Part b

In [200]:
Y = np.load("science2k-word-doc.npy")
Y

array([[-6.755691  , -6.755691  , -6.755691  , ...,  4.064107  ,
         5.093713  ,  3.707441  ],
       [-4.028205  , -4.028205  , -4.028205  , ..., -4.028205  ,
        -4.028205  , -4.028205  ],
       [-0.03370464, -1.132184  , -0.03370464, ...,  0.2539608 ,
         1.57568   ,  0.6594092 ],
       ...,
       [-0.1301101 , -0.1301101 , -0.1301101 , ..., -0.1301101 ,
        -0.1301101 , -0.1301101 ],
       [-0.05128021, -0.05128021, -0.05128021, ..., -0.05128021,
        -0.05128021, -0.05128021],
       [-0.06441435, -0.06441435, -0.06441435, ..., -0.06441435,
        -0.06441435, -0.06441435]])

In [201]:
k_vals = list(range(1,21))
for k in k_vals:
    kmeans = KMeans(n_clusters=k, random_state=0).fit(Y)

In [202]:
k = 7
kmeans = KMeans(n_clusters=k, random_state=0).fit(Y)
kmeans.labels_

array([5, 1, 2, ..., 2, 2, 2], dtype=int32)

In [203]:
n = 10
k_cluster_n = []
d = []
for cluster in range(k):
    d.append(kmeans.transform(Y)[:,cluster])
    k_cluster_n.append(np.sort(kmeans.transform(Y)[:,cluster])[:n])
k_cluster_n

[array([25.51990803, 25.74211179, 26.07022686, 26.13532673, 26.19134622,
        26.19775271, 26.20889089, 26.21847407, 26.23729024, 26.24180221]),
 array([39.47417635, 41.02108238, 41.34121343, 42.28546013, 42.31599052,
        42.36886816, 42.40678884, 42.43611206, 42.46772798, 42.47251495]),
 array([13.73764059, 13.79820661, 13.81601449, 13.85739855, 13.86997017,
        13.873625  , 13.89072011, 13.89625417, 13.90754595, 13.91609744]),
 array([29.99051097, 30.00189648, 30.09641791, 30.10177953, 30.16322754,
        30.17150709, 30.17885066, 30.18930876, 30.18996446, 30.19849696]),
 array([31.94773401, 34.46855177, 34.61054804, 34.61588261, 34.62000587,
        34.67053677, 34.6789498 , 34.70071327, 34.76572307, 34.82084916]),
 array([42.50891698, 42.90619149, 44.01121529, 45.2609505 , 50.81398743,
        55.09770444, 55.15616028, 55.27193499, 55.29084653, 55.29995086]),
 array([  0.        , 118.61620019, 119.40903601, 119.43605397,
        119.74810428, 120.1918912 , 120.40762687

In [204]:
data = pd.read_csv('science2k-vocab.txt', header=None)
data.columns = ["title"]

In [205]:
for i in range(len(d)):
    print("Cluster Group {}".format(i))
    w = list(d[i])
    ind = sorted(range(len(w)), key=lambda k: w[k])[:10]
    for j in ind:
        print(data['title'][j])
    print("\n")

Cluster Group 0
lcts
neas
proteorhodopsin
ag7
dnag
rory
lg268
pax8
aptamers
trxr


Cluster Group 1
end
org
sciencemag
mlin
noxa
kif17
rory
ifnar1
calcyon
mcry


Cluster Group 2
aptamers
dnag
rory
ag7
nompc
trxr
doxy
lg268
proteorhodopsin
lcts


Cluster Group 3
lcts
neas
autophagy
doxy
aptamers
dnag
trxr
pax8
ag7
proteorhodopsin


Cluster Group 4
end
ag7
nompc
trxr
neas
dnag
proteorhodopsin
aptamers
lcts
org


Cluster Group 5
sciencemag
org
end
vol
science
dnag
ag7
nompc
mcry
proteorhodopsin


Cluster Group 6
map
bacs
end
contigs
bac
mapped
polytene
shotgun
org
sciencemag




##### Comment on these results. How might such an algorithm be useful? What is different about clustering terms from clustering documents?

This algorithm captured the top 10 closest article terms to each cluster center. This may be useful by allowing us to use these words as key features to classify articles in a future model, think bag of words. One thing that stands out is the repeat use of words within these clusters. There is an overlap between some of the words which makes this clustering less distinct then with the documents.

In [ ]:
#Manual way of finding indices

In [177]:
# indices = []
# for top_10_list in range(len(k_cluster_n)):
#     for dist in k_cluster_n[top_10_list]:
#         ind = np.where(d[top_10_list] == dist)
#         indices.append(ind[0][0])
# print(indices)

[835, 1131, 1239, 983, 1298, 811, 812, 760, 899, 1010, 1281, 519, 90, 302, 574, 73, 797, 984, 159, 587, 519, 574, 453, 204, 0, 777, 1214, 790, 431, 1, 519, 574, 499, 122, 122, 122, 90, 0, 977, 977, 968, 997, 541, 367, 656, 519, 302, 1239, 1314, 1214, 983, 902, 302, 888, 760, 833, 1010, 812, 997, 856, 519, 574, 431, 302, 489, 122, 122, 122, 777, 769, 139, 1355, 1359, 1299, 380, 1326, 780, 862, 765, 736, 453, 519, 574, 0, 499, 1124, 90, 149, 1, 777, 1281, 139, 519, 574, 724, 442, 90, 1283, 177, 489]


In [122]:
# data = pd.read_csv('science2k-titles.txt', header=None)
# data.columns = ["title"]

1373

In [178]:
# ll = [a * 10 for a in range(1,k)]
# for l in range(len(ll)):
#     print("Cluster Group {}".format(l))
#     if ll[l] == 10:
#         j = 1
#     else:
#         j = ll[l-1]

#     for i in indices[j:ll[l]]:
#         print(data['title'][i])
#     print("\n")

Cluster Group 0
N-WASP Regulation: The Sting in the Tail
An Arresting Start for MAPK
Ubiquitination: More Than Two to Tango
Actin' up with Rac1
Bacterial Spelunkers
Replication Meets Cohesion
ER-to-Golgi Traffic: This Bud's for You
How to Get along: Friendly Microbes in a Hostile World
New Insights into an Old Modification


Cluster Group 1
The Formation of Chondrules at High Gas Pressures in the Solar Nebula
Algorithmic Gladiators Vie for Digital Glory
Heretical Idea Faces Its Sternest Test
Thermal, Catalytic, Regiospecific Functionalization of Alkanes
Reopening the Darkest Chapter in German Science
Information Storage and Retrieval through Quantum Phase
Synthesis and Characterization of Helical Multi-Shell Gold Nanowires
Quantum Dots as Tunable Kondo Impurities
Ambipolar Pentacene Field-Effect Transistors and Inverters
A Monoclinic Post-Stishovite Polymorph of Silica in the Shergotty Meteorite


Cluster Group 2
Algorithmic Gladiators Vie for Digital Glory
Reopening the Darkest Chapte