In [1]:
# SVD of a rank deficient matrix

import numpy as np

In [51]:
M = np.array([[1, 0, 3],
              [3, 7, 2],
              [2, -2, 8],
              [0, -1, 1],
              [5, 8, 7]])

np.linalg.matrix_rank(M)

2

In [52]:
# i. MT_M and M_MT

MT_M = np.matmul(M.transpose(), M)
print("MT_M = \n", MT_M)

print("\n")

M_MT = np.matmul(M, M.transpose())
print("M_MT = \n", M_MT)

MT_M = 
 [[ 39  57  60]
 [ 57 118  53]
 [ 60  53 127]]


M_MT = 
 [[ 10   9  26   3  26]
 [  9  62   8  -5  85]
 [ 26   8  72  10  50]
 [  3  -5  10   2  -1]
 [ 26  85  50  -1 138]]


In [53]:
# ii. Eigenvals

eigen_MT_M = np.linalg.eig(MT_M)
print("MT_M eigenvalues: \n", eigen_MT_M[0])

print("\n")

eigen_M_MT = np.linalg.eig(M_MT)
print("M_MT eigenvalues: \n", eigen_M_MT[0])

# the last two eigenvalues for M_MT are 0. Others are the same.

MT_M eigenvalues: 
 [ 2.14670489e+02 -1.68753900e-14  6.93295108e+01]


M_MT eigenvalues: 
 [ 2.14670489e+02 -7.77156117e-15  6.93295108e+01  1.23965036e-14
 -7.51374228e-16]


In [54]:
# iii. Eigenvectors

print("MT_M eigenvectors: \n", eigen_MT_M[1])

print("\n")

print("M_MT eigenvectors: \n", eigen_M_MT[1])

MT_M eigenvectors: 
 [[ 0.42615127  0.90453403 -0.01460404]
 [ 0.61500884 -0.30151134 -0.72859799]
 [ 0.66344497 -0.30151134  0.68478587]]


M_MT eigenvectors: 
 [[-0.16492942 -0.95539856  0.24497323 -0.05956233 -0.02427356]
 [-0.47164732 -0.03481209 -0.45330644  0.75120003 -0.04392963]
 [-0.33647055  0.27076072  0.82943965  0.32422341 -0.19816095]
 [-0.00330585  0.04409532  0.16974659  0.06197806  0.97262947]
 [-0.79820031  0.10366268 -0.13310656 -0.56849692  0.11047687]]


In [63]:
# iv. SVD

U, S, V = np.linalg.svd(M)

print(U[:,:2])

print("Diagonalized: \n", np.diag(S))

[[-0.16492942 -0.24497323]
 [-0.47164732  0.45330644]
 [-0.33647055 -0.82943965]
 [-0.00330585 -0.16974659]
 [-0.79820031  0.13310656]]
Diagonalized: 
 [[1.46516378e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 8.32643446e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.41374091e-16]]


In [68]:
# v. 1-D approximation


Mhat = U[:,:1].dot(np.diag(S[:1]).dot(V[:1,:]))

print(Mhat, "\n\n", M)

[[1.02978864 1.48616035 1.60320558]
 [2.94487812 4.24996055 4.58467382]
 [2.10085952 3.031898   3.27068057]
 [0.02064112 0.02978864 0.0321347 ]
 [4.9838143  7.19249261 7.75895028]] 

 [[ 1  0  3]
 [ 3  7  2]
 [ 2 -2  8]
 [ 0 -1  1]
 [ 5  8  7]]
